Stat = undefined
hostName = undefined
(->
  'use strict'
  chrome.runtime.onInstalled.addListener (details) ->
  #initialiize Stat variable
  Stat =
    data: {}
    cur: null
  #function that controll changing of tab

  tabChanged = (url) ->
    lst = undefined
    if Stat.cur
      lst = Stat.data[Stat.cur]
      lst.push new Date
    Stat.cur = url
    lst = Stat.data[url] or []
    lst.push new Date
    Stat.data[url] = lst
    Stat.data[url]

  getDomain = (url) ->
    myDomain = undefined
    myDomain = document.createElement('a')
    myDomain.href = url
    console.log 'domain = ' + myDomain.hostname
    myDomain.hostname

  updateBadge = (host) ->
    #set GET query to get the number of comment and setText to the Badge
    $.ajax
      url: 'http://127.0.0.1:8000/api/v1/comment/?currentUrl=' + host
      success: (result) ->
        chrome.browserAction.setBadgeText text: result.objects.length + ''
        return
    s
    return

  # almost the same with Browse_Track... 
  #...just set Bagde and get clear url, and call tabChange function
  chrome.tabs.onActivated.addListener (activeInfo) ->
    chrome.tabs.get activeInfo.tabId, (tab) ->
      host = undefined
      host = getDomain(tab.url)
      if host
        tabChanged host
      return updateBadge(host)
      chrome.extension.onConnect.addListener (port) ->
        #send message with my currentUrl to popup.js
        port.onMessage.addListener (a) ->
          #console.log("message recieved "+ a + " ");
          port.postMessage host
          return
        return
      hostName = host
      return
  return
).call this

# ---
# generated by js2coffee 2.0.3